project_name: asp-eks

builds:
  - id: cli
    main: ./main.go
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
    binary: asp-eks

archives:
  - format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: eimarfandino
    name: asp-eks
  draft: false
  prerelease: false

brews:
  - name: asp-eks
    description: "AWS profile switcher for EKS CLI access"
    homepage: "https://github.com/eimarfandino/asp-eks"
    tap:
      owner: eimarfandino
      name: homebrew-tap
      branch: main
    commit_author:
      name: Eimar Bot
      email: bot@eimarfandino.dev
    folder: Formula
    install: |
      bin.install "asp-eks"
    test: |
      system "#{bin}/asp-eks", "--help"
