project_name: asp-eks

builds:
  - id: default
    main: ./main.go
    goos: [darwin, linux, windows]
    goarch: [amd64, arm64]
    ldflags: ["-s -w"]
    binary: asp-eks

archives:
  - format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: eimarfandino
    name: asp-eks

brews:
  - name: asp-eks
    tap:
      owner: eimarfandino
      name: homebrew-tap
      branch: main
    description: "AWS profile switcher for EKS CLI access"
    homepage: "https://github.com/eimarfandino/asp-eks"
    commit_author:
      name: Eimar Bot
      email: bot@eimarfandino.dev
